name: CI

on:
  push:
    branches: [ "**" ]
  pull_request:
    branches: [ "**" ]

jobs:
  build:
    name: Build & Test (Node.js ${{ matrix.node-version }})
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [20.x]

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}

      - name: Check Node version
        run: node -v

      # Cache yarn and node_modules using yarn.lock
      - name: Cache yarn
        uses: actions/cache@v4
        with:
          path: |
            ~/.cache/yarn
            **/node_modules
          key: ${{ runner.os }}-yarn-${{ matrix.node-version }}-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-yarn-${{ matrix.node-version }}-

      - name: Install dependencies (Yarn)
        run: yarn install --frozen-lockfile

      - name: Run lint (if defined)
        run: yarn lint --silent || echo "no lint script"

      - name: Run tests (if defined)
        run: yarn test --silent || echo "no test script"

      - name: Upload test/coverage artifacts
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: test-artifacts-${{ matrix.node-version }}
          path: |
            test-results
            coverage
            junit-report.xml
